before_script:
  - apt-get update
  - apt-get install lftp

job1:
  script:
    - lftp -u $FTP_USER,$FTP_PASSWORD ftp.edistra.com -e "mirror -e -R ./build www/cronus-arena-tactics ; quit"
  only:
    - master