stages:
  - test
  - deploy

test:
  stage: test
  before_script:
    - npm install
  script:
    - karma start spec/support/karma.conf.js

deploy:
  stage: deploy
  before_script:
    - apt-get update
    - apt-get install lftp
  script:
    - lftp -u $FTP_USER,$FTP_PASSWORD ftp.edistra.com -e "mirror -e -R ./build www/cronus-arena-tactics ; quit"
  only:
    - master