image: node

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

stages:
  - setup
  - test
  - deploy

setup:
  stage: setup
  script:
    - npm install

test:
  stage: test
  script:
    - npm run serve_headless
    - npm run test

deploy:
  stage: deploy
  before_script:
    - apt-get update
    - apt-get install lftp
  script:
    - lftp -u $FTP_USER,$FTP_PASSWORD ftp.edistra.com -e "mirror -e -R ./build www/cronus-arena-tactics ; quit"
  only:
    - master